

app-configs:
  countries-directory: configs/country-codes.json
  regions-directory: configs/senegal-regions.json
  nationality-directory: configs/nationality.json
  jwt-name: javainuse
  sms-url: https://testgateway.ekenya.co.ke:8443/ServiceLayer/pgsms/send
  AccountsConfig-directory: configs/AccountsConfig.json
  walletServicesWrapper-directory: configs/walletServicesWrapper.json
  sms-from: FEPGROUP
  documents-storage: documents/

spring:
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: rmunialo
    url: jdbc:mysql://127.0.0.1:3306/tontines
    password: rMunialo@123
  servlet:
    multipart:
      max-file-size: 10000KB
      max-request-size: 10000KB
server:
  port: 8100
  ssl:
    key-store: classpath:sslkeystore.p12
    enabled: true
    key-store-type: PKCS12
    key-store-password: mypass
    key-alias: tomcat



